### ISSUE TITLE
Prepare the repo for the yarn auditing

### ISSUE THREAD

**Issue by sgkiokas** [camelotls/actions-npm-audit#21]
Despite the effort put in to make the repo more modular, in case of `yarn` extra changes are required. To properly tackle `yarn audit` we need to:

- update the Dockerfile in order to accept the `yarn.lock` file
- update the filtering mechanism to not only look for files including `package`
- add an input variable to indicate that we want to handle `yarn` specific auditing
- prepare the `yarn` output since it's not parsable by the Jira Inetgration action

For the last point, we need to:

- use `dirty-json` as a pre-processor to get a valid JSON format from the `yarn audit`
- recreate the JSON output fetching only the fields we are interested in (e.g. get the `id` of each vulnerability/advisory and then  per vulnerability fetch the fields you are interested in)

**Comment by pmegremis** [comment]
This has been fixed on #35.
